spring:
  datasource:
    username: root
    password: varun@123
    url: jdbc:mysql://localhost:3306/EmployeeInfoManagement
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL57Dialect

    
server:
  port: 8081